/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as PurchaseOrdersIndexRouteImport } from './routes/purchase-orders/index'
import { Route as PurchaseRequestsIndexRouteImport } from './routes/purchase-requests/index'
import { Route as PurchaseRequestsNewRouteImport } from './routes/purchase-requests/new'
import { Route as PurchaseOrdersIdIndexRouteImport } from './routes/purchase-orders/$id/index'
import { Route as PurchaseRequestsIdIndexRouteImport } from './routes/purchase-requests/$id/index'
import { Route as PurchaseRequestsIdEditRouteImport } from './routes/purchase-requests/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIndexRoute = PurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIndexRoute = PurchaseRequestsIndexRouteImport.update({
  id: '/purchase-requests/',
  path: '/purchase-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsNewRoute = PurchaseRequestsNewRouteImport.update({
  id: '/purchase-requests/new',
  path: '/purchase-requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdIndexRoute = PurchaseOrdersIdIndexRouteImport.update({
  id: '/purchase-orders/$id/',
  path: '/purchase-orders/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIdIndexRoute = PurchaseRequestsIdIndexRouteImport.update({
  id: '/purchase-requests/$id/',
  path: '/purchase-requests/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIdEditRoute = PurchaseRequestsIdEditRouteImport.update({
  id: '/purchase-requests/$id/edit',
  path: '/purchase-requests/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$id/edit': typeof PurchaseRequestsIdEditRoute
  '/purchase-orders/$id/': typeof PurchaseOrdersIdIndexRoute
  '/purchase-requests/$id/': typeof PurchaseRequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/inventory': typeof InventoryIndexRoute
  '/purchase-orders': typeof PurchaseOrdersIndexRoute
  '/purchase-requests': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$id/edit': typeof PurchaseRequestsIdEditRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdIndexRoute
  '/purchase-requests/$id': typeof PurchaseRequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/purchase-requests/new': typeof PurchaseRequestsNewRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase-orders/': typeof PurchaseOrdersIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/purchase-requests/$id/edit': typeof PurchaseRequestsIdEditRoute
  '/purchase-orders/$id/': typeof PurchaseOrdersIdIndexRoute
  '/purchase-requests/$id/': typeof PurchaseRequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/purchase-requests/new'
    | '/inventory/'
    | '/purchase-orders/'
    | '/purchase-requests/'
    | '/purchase-requests/$id/edit'
    | '/purchase-orders/$id/'
    | '/purchase-requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/purchase-requests/new'
    | '/inventory'
    | '/purchase-orders'
    | '/purchase-requests'
    | '/purchase-requests/$id/edit'
    | '/purchase-orders/$id'
    | '/purchase-requests/$id'
  id:
    | '__root__'
    | '/'
    | '/purchase-requests/new'
    | '/inventory/'
    | '/purchase-orders/'
    | '/purchase-requests/'
    | '/purchase-requests/$id/edit'
    | '/purchase-orders/$id/'
    | '/purchase-requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PurchaseRequestsNewRoute: typeof PurchaseRequestsNewRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PurchaseOrdersIndexRoute: typeof PurchaseOrdersIndexRoute
  PurchaseRequestsIndexRoute: typeof PurchaseRequestsIndexRoute
  PurchaseRequestsIdEditRoute: typeof PurchaseRequestsIdEditRoute
  PurchaseOrdersIdIndexRoute: typeof PurchaseOrdersIdIndexRoute
  PurchaseRequestsIdIndexRoute: typeof PurchaseRequestsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/': {
      id: '/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof PurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/': {
      id: '/purchase-requests/'
      path: '/purchase-requests'
      fullPath: '/purchase-requests/'
      preLoaderRoute: typeof PurchaseRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/new': {
      id: '/purchase-requests/new'
      path: '/purchase-requests/new'
      fullPath: '/purchase-requests/new'
      preLoaderRoute: typeof PurchaseRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders/$id/': {
      id: '/purchase-orders/$id/'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id/'
      preLoaderRoute: typeof PurchaseOrdersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/$id/': {
      id: '/purchase-requests/$id/'
      path: '/purchase-requests/$id'
      fullPath: '/purchase-requests/$id/'
      preLoaderRoute: typeof PurchaseRequestsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/$id/edit': {
      id: '/purchase-requests/$id/edit'
      path: '/purchase-requests/$id/edit'
      fullPath: '/purchase-requests/$id/edit'
      preLoaderRoute: typeof PurchaseRequestsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PurchaseRequestsNewRoute: PurchaseRequestsNewRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PurchaseOrdersIndexRoute: PurchaseOrdersIndexRoute,
  PurchaseRequestsIndexRoute: PurchaseRequestsIndexRoute,
  PurchaseRequestsIdEditRoute: PurchaseRequestsIdEditRoute,
  PurchaseOrdersIdIndexRoute: PurchaseOrdersIdIndexRoute,
  PurchaseRequestsIdIndexRoute: PurchaseRequestsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
